### ISSUE TITLE
Return with "Lua Create Object" returns received parameter instead

### ISSUE THREAD

**Issue by lp-pinheiro** [rdeioris/LuaMachine#22] opened 2021-01-13 19:14 UTC
If a Blueprint Function tries to return a LuaObject, it instead returns the received parameter.

I created a Blueprint function like this:

![image](https://user-images.githubusercontent.com/11857301/104497311-ec326080-55b8-11eb-8dbf-e02069c42462.png)
It receives a LuaValue as parameter (does nothing with it), then creates an object (Lua Create Object) from an asset and returns it.

Then I added that function to the global Lua table:
![image](https://user-images.githubusercontent.com/11857301/104497471-2996ee00-55b9-11eb-8c3c-47e1c73dfb01.png)

And called it from Lua, passing `"banana"` as the parameter:
![image](https://user-images.githubusercontent.com/11857301/104497540-46cbbc80-55b9-11eb-8db9-aa78ae3a98eb.png)

And this was printed:
![image](https://user-images.githubusercontent.com/11857301/104497680-7e3a6900-55b9-11eb-8381-dbc9990029fb.png)

As you can see, instead of print something like `userdata: 000002CD078BF7C8`, it printed the received parameter `"banana"`.

**ADDITIONAL INFO:** I managed to work around this bug by creating a table in the blueprint, putting the object inside the table, and then returning that table. That way, I am able to access the correct userdata by doing `TestObjectReturn("banana")[1]`.

**Comment by rdeioris** [comment] 2021-01-14 11:13
@lp-pinheiro hello, thanks for reporting, i am achecking it,  is this on latest master or on an official release ?

**Comment by rdeioris** [comment] 2021-01-14 11:36
@lp-pinheiro i did various tests, and i was not able to reproduce it. Is it possible you are calling TestObjectReturn from a coroutine ? in the current master there is a fix for object creation in coroutine: https://github.com/rdeioris/LuaMachine/commit/c1978cbd422fe19474aa4dde23f77489ab2b6df9

**Comment by lp-pinheiro** [comment] 2021-01-14 18:00
I tested on the release Marketplace 20201211.
And indeed, I was calling from a coroutine.

**Comment by rdeioris** [comment] 2021-01-14 18:03
@lp-pinheiro great, just use latest master and it should be fixed

**Closed** 2021-01-14 18:53 UTC
